[package]
name = "comic"
version = "0.1.0"
authors = ["chenej <chenej@gzyitop.com>"]

[dependencies]
file-fetcher = "0.1.1"
victoria-dom = "0.1"
reqwest = "0.8.2"
encoding = "0.2.33"
regex = "0.2.5"
error-chain = "0.11.0"
scoped_threadpool = "0.1.8"